# Generated by Django 2.2.19 on 2021-05-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210515_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_name',
        ),
    ]
