# Generated by Django 2.2.19 on 2021-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_name',
            field=models.CharField(choices=[(11, 'Hand Sanitizer'), (2, 'Surgical mask - Box (50 pcs)'), (101, 'Hair Growth and Nourishment Combo'), (19, 'Hairfall Control Combo'), (10, 'Clear Shampoo Men Cool Sport Menthol Anti Dandruff 180ml'), (22, 'Test01'), (20, '2')], default='select', max_length=100),
        ),
    ]
