# Generated by Django 2.2.19 on 2021-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_name',
        ),
    ]
