# Generated by Django 2.2.19 on 2021-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
