# Generated by Django 2.2.19 on 2021-05-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_name',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
