# Generated by Django 2.2.19 on 2021-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210518_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
