# Generated by Django 2.2.19 on 2021-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_n_time',
            field=models.DateTimeField(null=True),
        ),
    ]
